language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - yarn lint

notifications:
  email: false
  slack:
    rooms:
      - secure: "hHO3hN4v8w5XK8KGtBQlixjbshF9LtaTiuf0FTaIlELfZ4G//GntEfdP01MQcrYdNeSwPO4a1hz+/73tpLMSfDltMIYfojLD3DAo4e+H1sxjiiIlCY7+de8/DVKb581XZh2nTraJ/ztByZEKtCMWjL9uTCVXvltCyFjqyuXbW7ERj+jjlNELAEgxX+2BEqKm6sz2WIxKI9MDZanod8FZwV6xmjyoEIiyNAS6gCu2Np0w7zU6HCCHj7PzJ1DKwWffgn2nFOvjCWG5V87Nst7cw+qM7Ac9aVY9CtGARr7o6uAlWxgJKuR3WGI3+gY0Aa3Rg/JWziCLHtE10dGB6OPAzCdOSeB/9obxO2cHMEN5MeaZHDpoRKaqLDPNcjz274GY9XQsbxFtGdSKZbo0waOHIb3x84ofAQueBCUvogDZmWzZBDzCxofAd+PWDPUpqLdKURQlBSNAkL27WsD1pgF6v3MVLieMLcE81KphIvHXeUls6jkNFY8/GU3ugG2O9TRLQWOU4M6SMoaRzS+Pa0T2EjdweFbkMU6K2PrE0CFHtr9JRVCCRFP/0Woqe7Y74WTaxOXTvdv3ri5bjAIXqO1BPOLVBhHOhjVYqiup8oAwWXjkDIBMNX/SBdi9AsEMSfWb2G+H0e8waOYEjNr67l8nryzEwX4XQsj8dSVOub7A8RE="
