language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules

script:
  - yarn lint

notifications:
  email: false
  slack:
    rooms:
      - secure: 'Fm2p6OTjzeqiRc100sSX5dGuDg+7SjYyasuVZn09YCPWi64m5yTOwYZ2nNWDm2fa1Qdqy41mNSw3biuihd9dAcrfONqAbrR8x79mUgjQEHa2x/pFXVE9yXMFgAR4J8eyTlNQXpocmCciAW08O6maoEFQ2Q72x80uGGwUl7ag2XLxkpJXXnVvz9mTqY8gYNQmSyHCzNeRJJ8hGBXMHL4YSvgM+P0cZhAnB0JwBz+9xaDIoCN9i94ob8yQZHYehk/oG1rPS5gQdH09gHfGgigjhvQEIe6iST+YPfJR3BtQQsOVHmU01t4aKqc/DTExmJgk2IU71aiZ+nVCJnk9WwjOwzOQkmA9Om17gcaXifmHEZtsNa6pwMDO+FPO/NGLnGqMpXMV5t7Oi7OEAOUpKdreks28eqGEr08oxGAjHJ7ONKHPuH5aEGtgZWY/kumHWDywkUg13B3h1e0WvBeXUMviEtDdqCldpsw6hcxruaRBGlhUOr0BI+Ia9YQJ1plqg1UISRpx/Fg7872Hn1p/avslEy6IolxGoQWr7CPrKoP9gtOuOqXfNxSGms/Bh+FL7TdVTlg8ZSwOzw4jUxRr0QIyZ4aI/0eU9cXbrn/zxckw3zH0UbHbExosGiMsmDJkr6Ed+Po6xu/H+5RFT1gmT+yNzLN6AmO+InCJdwubm7brTUw='
