name: CI

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]
    steps:
      - name: Checking out
        uses: actions/checkout@v2
      - name: Getting branch name
        run: echo "::set-env name=BRANCH_NAME::${GITHUB_REF##*/}"
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: yarn install --ignore-scripts && npm rebuild node-sass
      - name: Build
        continue-on-error: true
        id: build
        run: |
          # build
          yarn build
          export STATUS="$?"

          # env
          echo "::set-env name=NODE_VERSION::${{ matrix.node_version }}"

          # status
          if [ "${STATUS}" -eq 0 ]; then
            echo '::set-output name=status::success'
            exit 0
          else
            echo '::set-output name=status::failure'
            exit 1
          fi
      - name: Prepare success Slack notification
        continue-on-error: true
        if: steps.build.outputs.status == 'success'
        run: echo "::set-env name=SLACK_CUSTOM_PAYLOAD::${SLACK_CUSTOM_PAYLOAD}"
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"react-ui-icheck","attachments":[{"color":"#2eb886","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *build* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has passed on Node.js {{ NODE_VERSION }}"}}]}]}'
      - name: Prepare failure Slack notification
        continue-on-error: true
        if: steps.build.outputs.status == 'failure'
        run: echo "::set-env name=SLACK_CUSTOM_PAYLOAD::${SLACK_CUSTOM_PAYLOAD}"
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"react-ui-icheck","attachments":[{"color":"#ed2f00","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *build* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has failed on Node.js {{ NODE_VERSION }}"}}]}]}'
      - name: Slack notification (codedsolar)
        continue-on-error: true
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CODEDSOLAR }}
      - name: Lint status
        run: |
          export EXIT=$("${SUCCESS}" && echo 0 || echo 1)
          exit "${EXIT}"
        env:
          SUCCESS: ${{ steps.build.outputs.status == 'success' }}

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]
    steps:
      - name: Checking out
        uses: actions/checkout@v2
      - name: Getting branch name
        run: echo "::set-env name=BRANCH_NAME::${GITHUB_REF##*/}"
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: yarn install --ignore-scripts && npm rebuild node-sass
      - name: Lint
        continue-on-error: true
        id: lint
        run: |
          # JavaScript
          export LINT_ISSUES_JS=$(yarn ci:eslint | grep Issues | awk -F' ' '{ print $2 }')

          # Markdown
          export LINT_ISSUES_MD=$(($(yarn ci:prettier:md | wc -l) - 5))
          export LINT_ISSUES_MD=$((LINT_ISSUES_MD < 0 ? 0 : LINT_ISSUES_MD))

          # SCSS
          export LINT_ISSUES_SCSS=$(($(yarn ci:prettier:scss | wc -l) - 5))
          export LINT_ISSUES_SCSS=$((LINT_ISSUES_SCSS < 0 ? 0 : LINT_ISSUES_SCSS))

          # YAML
          export LINT_ISSUES_YML=$(($(yarn ci:prettier:yml | wc -l) - 5))
          export LINT_ISSUES_YML=$((LINT_ISSUES_YML < 0 ? 0 : LINT_ISSUES_YML))

          # Issues
          export LINT_ISSUES=$((LINT_ISSUES_JS + LINT_ISSUES_MD + LINT_ISSUES_SCSS + LINT_ISSUES_YML))

          # env
          echo "::set-env name=LINT_ISSUES::${LINT_ISSUES}"
          echo "::set-env name=LINT_ISSUES_JS::${LINT_ISSUES_JS}"
          echo "::set-env name=LINT_ISSUES_MD::${LINT_ISSUES_MD}"
          echo "::set-env name=LINT_ISSUES_SCSS::${LINT_ISSUES_SCSS}"
          echo "::set-env name=LINT_ISSUES_YML::${LINT_ISSUES_YML}"
          echo "::set-env name=NODE_VERSION::${{ matrix.node_version }}"

          # lint
          yarn lint || true

          # status
          if [ ${LINT_ISSUES} -eq 0 ]; then
            echo '::set-output name=status::success'
            exit 0
          else
            echo '::set-output name=status::failure'
            exit 1
          fi
      - name: Prepare success Slack notification
        continue-on-error: true
        if: steps.lint.outputs.status == 'success'
        run: echo "::set-env name=SLACK_CUSTOM_PAYLOAD::${SLACK_CUSTOM_PAYLOAD}"
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"react-ui-icheck","attachments":[{"color":"#2eb886","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *lint* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has passed with no issues on Node.js {{ NODE_VERSION }}"}}]}]}'
      - name: Prepare failure Slack notification
        continue-on-error: true
        if: steps.lint.outputs.status == 'failure'
        run: echo "::set-env name=SLACK_CUSTOM_PAYLOAD::${SLACK_CUSTOM_PAYLOAD}"
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"react-ui-icheck","attachments":[{"color":"#ed2f00","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *lint* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has failed with *{{ LINT_ISSUES }}* issues on Node.js {{ NODE_VERSION }}"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*JavaScript (ESLint)*:\n{{ LINT_ISSUES_JS }}"},{"type":"mrkdwn","text":"*Markdown (Prettier)*:\n{{ LINT_ISSUES_MD }}"},{"type":"mrkdwn","text":"*SCSS (Prettier)*:\n{{ LINT_ISSUES_SCSS }}"},{"type":"mrkdwn","text":"*YAML (Prettier)*:\n{{ LINT_ISSUES_YML }}"}]}]}]}'
      - name: Slack notification (codedsolar)
        continue-on-error: true
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CODEDSOLAR }}
      - name: Lint status
        run: |
          export EXIT=$("${SUCCESS}" && echo 0 || echo 1)
          exit "${EXIT}"
        env:
          SUCCESS: ${{ steps.lint.outputs.status == 'success' }}
