name: Deploy

on:
  push:
    branches:
      - main

permissions: read-all

env:
  NODE_ENV: development
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  production:
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node_version: [14.x]
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set a job-wide environment variables
        run: |
          echo "APP_REVISION=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=${{ secrets.DOCKER_REGISTRY_HOST }}/react-ui-icheck-website" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
      - name: Set up Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        id: node
        with:
          node-version: ${{ matrix.node_version }}
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          status: in-progress
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
      - name: Install dependencies
        run: yarn install --ignore-scripts
      - name: Build
        id: build
        run: yarn build
        env:
          APP_PUBLIC_PATH: /react-ui-icheck/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to the private registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Generate an image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=true
          images: ${{ env.DOCKER_IMAGE_NAME }}
          labels: maintainer=victor@popkov.me
      - name: Build an image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          cache-to: type=inline
          context: .
          file: ./Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7
          pull: true
          push: ${{ !env.ACT && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
      - name: Add Docker certificates to access the remote host
        if: ${{ !env.ACT }}
        run: |
          mkdir -p "${DOCKER_CERT_PATH}"
          echo "${{ secrets.DOCKER_TLS_CA }}" > "${DOCKER_CERT_PATH}/ca.pem"
          echo "${{ secrets.DOCKER_TLS_CERT }}" > "${DOCKER_CERT_PATH}/cert.pem"
          echo "${{ secrets.DOCKER_TLS_KEY }}" > "${DOCKER_CERT_PATH}/key.pem"
          chmod 400 "${DOCKER_CERT_PATH}/ca.pem"
          chmod 400 "${DOCKER_CERT_PATH}/cert.pem"
          chmod 400 "${DOCKER_CERT_PATH}/key.pem"
        env:
          DOCKER_CERT_PATH: /home/runner/.docker/deploy
      - name: Deploy Docker Stack
        if: ${{ !env.ACT }}
        run: |
          docker stack rm "${{ secrets.DOCKER_STACK_NAME }}"
          docker stack deploy \
            --with-registry-auth \
            --resolve-image=always \
            --compose-file=docker-stack.yml \
            --prune \
            "${{ secrets.DOCKER_STACK_NAME }}"
        env:
          DOCKER_CERT_PATH: /home/runner/.docker/deploy/
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          DOCKER_STACK_NODE_HOSTNAME: ${{ secrets.DOCKER_STACK_NODE_HOSTNAME }}
          DOCKER_TLS_VERIFY: 1
          LOKI_PIPELINE_STAGE_FILE: ${{ secrets.LOKI_PIPELINE_STAGE_FILE }}
          LOKI_URL: ${{ secrets.LOKI_URL }}
          NGINX_CONF: ${{ secrets.NGINX_CONF }}
          TRAEFIK_HOSTNAME: github.victorpopkov.com
          TRAEFIK_NAME: ${{ secrets.TRAEFIK_NAME }}
          TRAEFIK_PATH_PREFIX: /react-ui-icheck/
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
