name: Deploy

on:
  push:
    branches:
      - master

jobs:
  production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14.x]
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set a job-wide environment variables
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "GITHUB_JOB_NAME=production" >> $GITHUB_ENV
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: yarn install --ignore-scripts && npm rebuild node-sass
      - name: Build
        id: build
        run: |
          # build
          export APP_REVISION="$(git rev-parse HEAD)"
          yarn build
          export STATUS="$?"

          # env
          echo "APP_REVISION=${APP_REVISION}" >> $GITHUB_ENV
          echo "NODE_VERSION=${{ matrix.node_version }}" >> $GITHUB_ENV

          # status
          if [ "${STATUS}" -eq 0 ]; then
            exit 0
          else
            exit 1
          fi
        env:
          APP_PUBLIC_PATH: /react-ui-icheck/
      - name: Add Docker certificates to access the remote host
        run: |
          mkdir -p "${DOCKER_CERT_PATH}"
          echo "${DOCKER_TLS_CA}" > "${DOCKER_CERT_PATH}/ca.pem"
          echo "${DOCKER_TLS_CERT}" > "${DOCKER_CERT_PATH}/cert.pem"
          echo "${DOCKER_TLS_KEY}" > "${DOCKER_CERT_PATH}/key.pem"
          chmod 400 "${DOCKER_CERT_PATH}/ca.pem"
          chmod 400 "${DOCKER_CERT_PATH}/cert.pem"
          chmod 400 "${DOCKER_CERT_PATH}/key.pem"
        env:
          DOCKER_CERT_PATH: /home/runner/.docker/deploy
          DOCKER_TLS_CA: ${{ secrets.DEPLOY_DOCKER_TLS_CA }}
          DOCKER_TLS_CERT: ${{ secrets.DEPLOY_DOCKER_TLS_CERT }}
          DOCKER_TLS_KEY: ${{ secrets.DEPLOY_DOCKER_TLS_KEY }}
      - name: Build Docker image
        run: |
          docker build --tag "${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}" .
          echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}" >> $GITHUB_ENV
        env:
          DOCKER_CERT_PATH: /home/runner/.docker/deploy
          DOCKER_HOST: tcp://codedsolar.com:2376
          DOCKER_IMAGE: victorpopkov/react-ui-icheck-website
          DOCKER_IMAGE_TAG: latest
          DOCKER_TLS_VERIFY: 1
      - name: Deploy Docker Stack
        run: |
          docker stack rm "${DOCKER_STACK_NAME}"
          docker stack deploy --with-registry-auth --resolve-image=always --compose-file=docker-stack.yml --prune "${DOCKER_STACK_NAME}"
        env:
          DOCKER_CERT_PATH: /home/runner/.docker/deploy
          DOCKER_HOST: tcp://codedsolar.com:2376
          DOCKER_STACK_NAME: github_react_ui_icheck_website
          DOCKER_STACK_TRAEFIK_HOST: github.victorpopkov.com
          DOCKER_STACK_TRAEFIK_NAME: github-react-ui-icheck-website
          DOCKER_STACK_TRAEFIK_PATH_PREFIX: /react-ui-icheck/
          DOCKER_TLS_VERIFY: 1
      - name: Prepare success Slack notification
        if: success()
        run: echo "SLACK_CUSTOM_PAYLOAD=${SLACK_CUSTOM_PAYLOAD}" >> $GITHUB_ENV
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"react-ui-icheck","attachments":[{"color":"#2eb886","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has passed on Node.js {{ NODE_VERSION }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has passed on Node.js *{{ NODE_VERSION }}*"}}]}]}'
      - name: Prepare failure Slack notification
        if: failure()
        run: echo "SLACK_CUSTOM_PAYLOAD=${SLACK_CUSTOM_PAYLOAD}" >> $GITHUB_ENV
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"react-ui-icheck","attachments":[{"color":"#ed2f00","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has failed on Node.js {{ NODE_VERSION }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has failed on Node.js *{{ NODE_VERSION }}*"}}]}]}'
      - name: Send Slack notification
        if: always()
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CODEDSOLAR }}
